name: Build and Deploy

on:
  push:
    branches: [main]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build-en:
    name: Build English site
    uses: ./.github/workflows/_build.yml
    with:
      artifact: dist-en
      lang: en
      locale: en-US

  deploy-en:
    name: Deploy English site
    needs: build-en
    uses: ./.github/workflows/_deploy.yml
    with:
      domain: en.gwen.works
      netlify-project: gwennlbh-portfolio-en
      artifact: dist-en

  build-fr:
    name: Build French site
    uses: ./.github/workflows/_build.yml
    with:
      artifact: dist-fr
      lang: fr
      locale: fr-FR

  deploy-fr:
    name: Deploy French site
    needs: build-fr
    uses: ./.github/workflows/_deploy.yml
    with:
      domain: fr.gwen.works
      netlify-project: gwennlbh-portfolio-fr
      artifact: dist-fr
