name: Trigger build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { lang: en, language: english, locale: en-US }
          - { lang: fr, language: french,  locale: fr-FR }
    environment:
      name: ${{ matrix.locale }} build repository
      url: https://github.com/gwennlbh/portfolio-build-${{ matrix.lang }}
    steps:
      - name: Dispatch workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: gwennlbh/portfolio-build-${{ matrix.lang }}
          event-type: build
          client-payload: '{ 
            "ref": "${{ github.sha }}", 
            "lang": "${{ matrix.lang }}", 
            "language": "${{ matrix.language }}",
            "locale": "${{ matrix.locale }}"
          }'
          token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}

