name: Trigger build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, fr]
    environment:
      name: Repository ${{ matrix.language}}
      url: https://github.com/gwennlbh/portfolio-build-${{ matrix.language }}
    steps:
      - name: Dispatch workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: gwennlbh/portfolio-build-${{ matrix.language }}
          event-type: build
          client-payload: '{ "ref": "${{ github.sha }}", "lang": "${{ matrix.language }}" }'
          token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
